version: "2"
services:

  dispatcher:
    ports:
      - "444:80"

  db:
    ports:
      - "8890:8890"

  resource:
    ports:
      - "555:80"

  swarm-admin:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  swarm-logger:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    driver: bridge
